name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'           # Aquí especificamos Java 22
          distribution: 'adoptopenjdk'  # Usamos AdoptOpenJDK o cambia a otra distribución como 'zulu' si prefieres

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: mi-proyecto
          sonar-project-name: Mi Proyecto
          sonar-project-version: '1.0'
