name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token del proyecto
          SONAR_HOST_URL: https://sonarcloud.io   # URL de tu instancia de SonarQube (o SonarCloud)
          SONAR_PROJECT_KEY: megastore-nico      # Clave del proyecto (nombrado según el repositorio)
          SONAR_PROJECT_NAME: megastore-nico     # Nombre del proyecto (puedes usar el nombre del repositorio)
          SONAR_PROJECT_VERSION: '1.0'           # Versión del proyecto
        run: |
          sonar-scanner
